trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install vsce'


- script: |
    vsce publish -p $(vsce.token)

  displayName: 'Run a multi-line script'
