trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

env:
  VSCE.TOKEN: $(vsce.token)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install vsce'

- script: |
    vsce publish -p $env:VSCE.TOKEN

  displayName: 'Run a multi-line script'
